package cainjector

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

// generateEnvScript writes a shell script setting runtime CA environment variables.
func generateEnvScript(certPath, outputPath string, logger *slog.Logger) error {
	absCertPath, err := filepath.Abs(certPath)
	if err != nil {
		return fmt.Errorf("failed to resolve absolute cert path: %w", err)
	}

	absOutputPath, err := filepath.Abs(outputPath)
	if err != nil {
		return fmt.Errorf("failed to resolve absolute output path: %w", err)
	}

	parentDir := filepath.Dir(absOutputPath)
	if err := os.MkdirAll(parentDir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", parentDir, err)
	}

	leaf := absCertPath
	bundle := ResolveBundle(leaf)
	vars := RuntimeVars(leaf, bundle)

	var b strings.Builder
	fmt.Fprintf(&b, "#!/bin/bash\n# Auto-generated by proxy CA injector\n# Source this file: source %s\n\n", absOutputPath)
	for _, kv := range vars {
		fmt.Fprintf(&b, "export %s=%q\n", kv[0], kv[1])
	}

	if err := os.WriteFile(absOutputPath, []byte(b.String()), 0755); err != nil {
		return fmt.Errorf("failed to write env script to %s: %w", absOutputPath, err)
	}

	if err := os.Chmod(absOutputPath, 0755); err != nil {
		return fmt.Errorf("failed to chmod env script %s: %w", absOutputPath, err)
	}

	if logger != nil {
		logger.Info("Env script generated", "output_path", absOutputPath, "leaf", leaf, "bundle", bundle)
	}

	return nil
}
