package cainjector

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
)

// generateEnvScript writes a shell script setting runtime CA environment variables.
func generateEnvScript(certPath, outputPath string, logger *slog.Logger) error {
	absCertPath, err := filepath.Abs(certPath)
	if err != nil {
		return fmt.Errorf("failed to resolve absolute cert path: %w", err)
	}

	absOutputPath, err := filepath.Abs(outputPath)
	if err != nil {
		return fmt.Errorf("failed to resolve absolute output path: %w", err)
	}

	parentDir := filepath.Dir(absOutputPath)
	if err := os.MkdirAll(parentDir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", parentDir, err)
	}

	content := fmt.Sprintf(`#!/bin/bash
# Auto-generated by proxy CA injector
# Source this file: source %s

export REQUESTS_CA_BUNDLE="%s"
export CURL_CA_BUNDLE="%s"
export SSL_CERT_FILE="%s"
export NODE_EXTRA_CA_CERTS="%s"
export SSL_CERT_DIR=""
export GIT_SSL_CAINFO="%s"
`, absOutputPath, absCertPath, absCertPath, absCertPath, absCertPath, absCertPath)

	if err := os.WriteFile(absOutputPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write env script to %s: %w", absOutputPath, err)
	}

	// Ensure permissions are 0755 even if umask modified it or file already existed
	if err := os.Chmod(absOutputPath, 0755); err != nil {
		return fmt.Errorf("failed to chmod env script %s: %w", absOutputPath, err)
	}

	if logger != nil {
		logger.Info("Env script generated", "output_path", absOutputPath)
	}

	return nil
}
