package cainjector

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	DefaultEnvironmentFile = "/etc/environment"
	DefaultProfileScript   = "/etc/profile.d/t9-proxy-ca.sh"
	GuestLeafCertPath      = "/usr/local/share/ca-certificates/t9-proxy-ca.crt"
	GuestLeafPEMPath       = "/etc/ssl/certs/t9-proxy-ca.pem"
	nodeOpenSSLCAFlag      = "--use-openssl-ca"
)

var systemBundleCandidates = []string{
	"/etc/ssl/certs/ca-certificates.crt",
	"/etc/pki/tls/certs/ca-bundle.crt",
	"/etc/ssl/cert.pem",
}

// ResolveBundle returns the distro CA bundle if present, otherwise leaf.
func ResolveBundle(leaf string) string {
	for _, p := range systemBundleCandidates {
		st, err := os.Stat(p)
		if err == nil && st.Size() > 0 {
			return p
		}
	}
	return leaf
}

// RuntimeVars is the single list of CA-related environment variables.
// Bundle-backed vars must be the full trust store so exempt (non-MITM) TLS still
// verifies public CAs. NODE_EXTRA_CA_CERTS is additive and uses the leaf.
func RuntimeVars(leaf, bundle string) [][2]string {
	if bundle == "" {
		bundle = leaf
	}
	return [][2]string{
		{"SSL_CERT_FILE", bundle},
		{"CURL_CA_BUNDLE", bundle},
		{"REQUESTS_CA_BUNDLE", bundle},
		{"AWS_CA_BUNDLE", bundle},
		{"GIT_SSL_CAINFO", bundle},
		{"PIP_CERT", bundle},
		{"NODE_EXTRA_CA_CERTS", leaf},
		{"npm_config_cafile", bundle},
		{"SSL_CERT_DIR", ""},
		{"NODE_OPTIONS", nodeOpenSSLCAFlag},
	}
}

func runtimeVarKeys() map[string]struct{} {
	keys := make(map[string]struct{})
	for _, kv := range RuntimeVars("x", "y") {
		keys[kv[0]] = struct{}{}
	}
	return keys
}

func mergeNodeOptions(existing string) string {
	existing = strings.TrimSpace(existing)
	if existing == "" {
		return nodeOpenSSLCAFlag
	}
	fields := strings.Fields(existing)
	for _, f := range fields {
		if f == nodeOpenSSLCAFlag {
			return existing
		}
	}
	return existing + " " + nodeOpenSSLCAFlag
}

func upsertEnvironmentFile(path string, leaf, bundle string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}

	preserved := make([]string, 0)
	oldNode := ""
	if f, err := os.Open(path); err == nil {
		sc := bufio.NewScanner(f)
		ours := runtimeVarKeys()
		for sc.Scan() {
			line := sc.Text()
			trim := strings.TrimSpace(line)
			if trim == "" || strings.HasPrefix(trim, "#") {
				preserved = append(preserved, line)
				continue
			}
			key, val, ok := strings.Cut(trim, "=")
			if !ok {
				preserved = append(preserved, line)
				continue
			}
			key = strings.TrimSpace(key)
			if _, hit := ours[key]; hit {
				if key == "NODE_OPTIONS" {
					oldNode = strings.Trim(strings.TrimSpace(val), `"'`)
				}
				continue
			}
			preserved = append(preserved, line)
		}
		_ = f.Close()
		if err := sc.Err(); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	vars := RuntimeVars(leaf, bundle)
	out := strings.Builder{}
	for _, line := range preserved {
		out.WriteString(line)
		out.WriteByte('\n')
	}
	for _, kv := range vars {
		val := kv[1]
		if kv[0] == "NODE_OPTIONS" {
			val = mergeNodeOptions(oldNode)
		}
		fmt.Fprintf(&out, "%s=%s\n", kv[0], val)
	}
	return os.WriteFile(path, []byte(out.String()), 0644)
}

func writeProfileScript(path, leaf, bundle string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	vars := RuntimeVars(leaf, bundle)
	b := strings.Builder{}
	b.WriteString("#!/bin/sh\n# Auto-generated by t9-ca-inject — proxy MITM CA for guest runtimes\n")
	for _, kv := range vars {
		val := kv[1]
		if kv[0] == "NODE_OPTIONS" {
			val = nodeOpenSSLCAFlag
		}
		fmt.Fprintf(&b, "export %s=%q\n", kv[0], val)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0755); err != nil {
		return err
	}
	return os.Chmod(path, 0755)
}
